# Generated by Django 4.2.5 on 2023-10-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LB_API', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'follow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Followed',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'followed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserReported',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'userReported',
                'managed': False,
            },
        ),
    ]
