# Generated by Django 4.2.5 on 2023-10-10 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LB_API', '0003_follow_followed_userreported'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReported',
        ),
    ]
